### PR TITLE
chore: possible fix for cjs builds

### PR DESCRIPTION
**Pull request by carsonfarmer**
Hey @asutula and @joewagner can you please take a look at this and let me know if it is going to work for you? It would be great if you could test this locally to make sure it is working. I've created the cjs tests to help, but just to make sure it'll work for hardhat?

### CODE REVIEW

**Comment by asutula** [comment]
This seems to have fixed the problem for using `@tableland/sqlparser` from the cjs `@tableland/sdk`, but now the same problem is cropping up for a package we don't own, `camelize-ts`:
```
> node dist/cjs/up.js
/Users/aaron/Code/textile/local-tableland/node_modules/@tableland/sdk/dist/cjs/validator/receipt.js:7
const camelize_ts_1 = __importDefault(require("camelize-ts"));
                                      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/aaron/Code/textile/local-tableland/node_modules/camelize-ts/dist/index.js from /Users/aaron/Code/textile/local-tableland/node_modules/@tableland/sdk/dist/cjs/validator/receipt.js not supported.
```

I guess this means that if we intend to have a cjs build of our package, all dependencies we use must provide a cjs build?

**Comment by asutula** [comment]
So, this PR is looking good for this repo, but looks like we'll need to track this issue in `js-tableland` repo.

**Comment by carsonfarmer** [comment]
Ok, so are we good to merge this in here then @asutula . And then I'll create a separate issue for the camelize stuff in js-tableland.

**Review by joewagner — COMMENTED** [review]
I'm trying to build by doing `npm install` then `npm run build`.
When I run build, it stops and says I have to install ` esbuild@0.17.4`.  Is there a reason that isn't being installed via npm install?

**Comment by carsonfarmer** [comment]
Yeah that's correct. It is just using `npx` to lazily install the dep when it is needed.

**Comment by carsonfarmer** [comment]
hey @joewagner and/or @asutula I need a final 👍 on this one it seems

**Review by asutula — APPROVED** [review]

**Pull request merged**
