### PR TITLE
Deprecate this repo

### PR DESCRIPTION
**Pull request by joewagner**
This replaces the README with a link to the new repo.
@carsonfarmer do you have the ability to turn off dependabot for this repo?

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Yes I do

**Comment by joewagner** [comment]
> Yes I do. But note also that this PR should probably remove the dependabot config from the .github folder: https://github.com/tablelandnetwork/wasm-sqlparser/tree/main/.github. I can also "freeze" this repo etc but we don't want to do that before we have closed tickets etc.

Nice! @carsonfarmer I removed `dependabot.yml`. As far as steps to freeze this, should we:
- merge this
- close all the pull requests
- disable dependabot?

**Review by carsonfarmer — APPROVED** [review]
Nice, I think this'll leave it in a good state.

**Comment by carsonfarmer** [comment]
I've disabled dependabot in settings, so we won't see any new ones after this PR is merged.

**Pull request merged**
